---
- name: Add php repo
  apt_repository:
    repo: "{{ php_repo }}"
    update_cache: yes
    state: present

- name: Install php
  apt:
    state: latest
    name: "{{ item }}"
  with_items: "{{ php_packages }}"

- name: Install php custom packages
  apt:
    state: latest
    name: "{{ item }}"
  with_items: "{{ php_packages_custom|default('') }}"
  when: php_packages_custom is defined

- name: Install pear packages
  pear:
    state: present
    name: "{{ item }}"
  with_items: "{{ php_pear_packages|default('') }}"
  when: php_pear_packages is defined
