---
- name: Add php repo
  apt_repository:
    repo: "{{ php_repo }}"
    update_cache: yes
    state: present

- name: Install php
  apt:
    state: latest
    name: "{{ php_packages|default('') }}"

- name: Install php custom packages
  apt:
    state: latest
    name: "{{ php_packages_custom|default('') }}"
  when: php_packages_custom is defined
  notify:
    - "Restart fpm"

- name: Install pear packages
  pear:
    state: present
    name: "{{ item }}"
  with_items: "{{ php_pear_packages|default('') }}"
  when: php_pear_packages is defined
  notify:
    - "Restart fpm"

- name: Configure php fpm
  lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/php.ini"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
  with_items: " {{ php_config_lines|default('') }}"
  when: php_config_lines is defined
  notify:
    - "Restart fpm"

- name: Configure php cli
  lineinfile:
    path: "/etc/php/{{ php_version }}/cli/php.ini"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
  with_items: " {{ php_config_lines|default('') }}"
  when: php_config_lines is defined
  notify:
    - "Restart fpm"
